import pywhatkit
import telebot
import wikipedia
from wikipedia.exceptions import PageError
from datetime import time, date, datetime
from bs4 import BeautifulSoup
import requests
from gitrepo import makerepo
import pyautogui
import urllib
import os
import ctypes
import time as t
#######################################
API_KEY=''
bot = telebot.TeleBot(API_KEY)
some_id = 11111111111
#######################################

cmd1='/repo + repo_name : to create new repository on github'
cmd2='/wake_up : to send message at 07:00 every day'
cmd3='Who is + name  : to search for sommone and send it'
cmd4='What is + sommthing : to seach somthing in wikipidia and send it'
cmd5='Play + name : to play a video on youtube'
cmd6='Idea : to scrap new ideas generated by AI and send it'
cmd7='/win + open + name : to open a disktop app'
cmd8='/win + lock : Locking the computer'
cmd9='/screen : to take a screenchot and send it'
cmd10='/shutdown : to shutdown the computer'
cmd11='Emoji : get a random emoji'

def sedme():
    try:


        @bot.message_handler(commands=['help'])
        def createrepo(message):
                    bot.send_message(message.chat.id, "---------------- 🇭​​​​​🇪​​​​​🇱​​​​​🇵 📜 ---------------- \n\n\n​​​​​𝗔𝗹𝗹 𝕔𝕠𝕞𝕞𝕒𝕟𝕕𝕤 𝘆𝗼𝘂 𝗻𝗲𝗲𝗱 𝘁𝗼 𝗸𝗻𝗼𝘄 📝🔥 : \n\n\n▶️   "+cmd7+"\n\n▶️  "+cmd9+"\n\n▶️  "+cmd1+"\n\n▶️  "+cmd2+"\n\n▶️  "+cmd8+"\n\n▶️  "+cmd10+"\n\n▶️  "+cmd3+"\n\n▶️  "+cmd4+"\n\n▶️  "+cmd5+"\n\n▶️  "+cmd6+"\n\n▶️  "+cmd11+"\n\n🤖")
                    
        @bot.message_handler(commands=['start'])
        def createrepo(message):
                    bot.send_message(message.chat.id, "---------------- 🆂🆃🅰🆁🆃 ---------------- \n\n\n​​​​​𝗔𝗹𝗹 𝕔𝕠𝕞𝕞𝕒𝕟𝕕𝕤 𝘆𝗼𝘂 𝗻𝗲𝗲𝗱 𝘁𝗼 𝗸𝗻𝗼𝘄 📝🔥 : \n\n\n▶️   "+cmd7+"\n\n▶️  "+cmd9+"\n\n▶️  "+cmd1+"\n\n▶️  "+cmd2+"\n\n▶️  "+cmd8+"\n\n▶️  "+cmd10+"\n\n▶️  "+cmd3+"\n\n▶️  "+cmd4+"\n\n▶️  "+cmd5+"\n\n▶️  "+cmd6+"\n\n▶️  "+cmd11+"\n\n\n ᴘʟᴀʏ /𝕙𝕖𝕝𝕡 ᴛᴏ sᴇᴇ ᴛʜɪs ᴀ ɢᴀɪɴ 🤖")
                    

        @bot.message_handler(commands=['repo'])
        def createrepo(message):
                try:
                    msg = message.text
                    msg = msg.replace('/repo', '')
                    bot.send_message(message.chat.id, "Creating a new repository named '"+msg+" '  ...")
                    
                    
                    bot.send_message(message.chat.id, makerepo(msg))
                except wikipedia.exceptions.PageError as e:
                    bot.send_message(message.chat.id, e)
        
        @bot.message_handler(commands=['screen'])
        def capture_screen(message):
            try:
                        bot.send_message(message.chat.id, "Taking Screenshot ..")
                        screenimage = pyautogui.screenshot('screen.png')
                        t.sleep(1)
                        screenimage.save(r"screen.png")
                        t.sleep(1)
                        bot.send_photo(message.chat.id,photo = open(r"screen.png",'rb'))
            except wikipedia.exceptions.PageError as e:
                    bot.send_message(message.chat.id, e)  


        @bot.message_handler(commands=['win'])
        def capture_screen(message):
            msg = message.text
            try:
                msg = msg.replace('/win ', '')

                if 'lock' in msg:
                            bot.send_message(message.chat.id, "Locking the computer ..")
                            ctypes.windll.user32.LockWorkStation()
                            t.sleep(1)
                            bot.send_message(message.chat.id, "Computer is Locked.")
                elif 'open' in msg:
                            msg = msg.replace('open ', '')
                            bot.send_message(message.chat.id, "Opening "+msg+" ..")
                            pyautogui.keyDown('winleft')
                            pyautogui.press('r')
                            pyautogui.keyUp('winleft')
                            pyautogui.write(msg)
                            pyautogui.press('enter')
            except wikipedia.exceptions.PageError as e:
                    bot.send_message(message.chat.id, e)  




        @bot.message_handler(commands=['shutdown'])
        def shutdown(message):
                try:
                    bot.send_message(message.chat.id, "🛑 Do you wish to shutdown your computer ?\n( /sh yes  ＯＲ  /sh no )")
                except wikipedia.exceptions.PageError as e:
                    bot.send_message(message.chat.id, e)


        @bot.message_handler(commands=['sh'])
        def yesno(message):
                shutdown = message.text
                if 'yes' in shutdown:
                    os.system("shutdown /s /t 1")
                else:
                    bot.send_message(message.chat.id, "Shutdown Stopped.")

        @bot.message_handler(commands=['wake_up'])
        def waking_up(message):
                try:
                    bot.send_message(message.chat.id,"Waking up at : '07:00'")
                    t.sleep(2)
                    from Wakeup import wake_up
                    wake_up()
                except wikipedia.exceptions.PageError as e:
                    bot.send_message(message.chat.id, e)
       


        

        @bot.message_handler(func=lambda m: True)
        def repeat(message):
            msg = message.text
            if 'Who is' in msg:
                msg = msg.replace('Who is', '')
                person = wikipedia.search(msg)
                for p in person:
                    bot.send_message(message.chat.id, p) 
            elif 'What is' in msg:
                try:
                    msg = msg.replace('What is', '')
                    bot.send_message(message.chat.id, wikipedia.summary(msg)) 
                except wikipedia.exceptions.PageError as e:
                    bot.send_message(message.chat.id, e)
            elif 'Play' in msg:
                try:
                    msg = msg.replace('Play', '')
                    bot.send_message(message.chat.id, "Playing "+msg+" ..") 
                    pywhatkit.playonyt(msg)
                except wikipedia.exceptions.PageError as e:
                    bot.send_message(message.chat.id, e)
            elif 'Idea'  in msg:
                bot.send_message(message.chat.id, 'Idea you might like :')
                # 1.Fetch the pages (write the website you wish to scrape within parentheses)
                result = requests.get("https://thisideadoesnotexist.com/")
                # 2.Get the page content
                content = result.text
                # 3. Create the soup
                soup = BeautifulSoup(content, "lxml")
                element = soup.find('h2')
                bot.send_message(message.chat.id, element)
            elif 'Emoji' in msg:
                result = requests.get("https://emojipedia.org/random/")
                content = result.text
                soup = BeautifulSoup(content, "lxml")
                element = soup.find('input',{"class": "emoji-copy copy-paste__data"}).get('value')
                bot.send_message(message.chat.id, element)
            else:
                bot.send_message(message.chat.id, "sorry i don't understand your Command 💀")





        bot.polling()



    except:
        bot.send_message(some_id,'👁️‍🗨️ try again')
        sedme()

while True:
    sedme()


